import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./navbar";
import Form from "./Form";
import Hero1 from "./hero1";
import Footer from "./Footer";
import Hero2 from "./tracking";
import Searchbar from "./searchbar";
import Newsletter from "./newsletter";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main class="bg-white">
        <Hero1 />
        <Newsletter />
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
