import React, { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Navbar from "../components/navbar";
import Form from "../components/Form";
import Footer from "../components/Footer";
import Tracking from "../components/tracking";
import { FypContext } from "../context/context";

export default function Trackingpage() {
  const router = useRouter();
  const { trackingId } = router.query;

  const { baseUrl } = useContext(FypContext);
  const [localAccessToken, setLocalAccessToken] = useState("");
  const [trackingDetails, setTrackingDetails] = useState("");

  useEffect(() => {
    const storedState = localStorage.getItem("Access Token");
    if (storedState) {
      setLocalAccessToken(storedState);
      getTrackingDetails(storedState);
    }
    // console.log(`Access Token: ${accessToken}`);
    console.log(`Local Token: ${localAccessToken}`);
  }, []);

  const getTrackingDetails = async (accessToken) => {
    try {
      const url = `${baseUrl}orders/${trackingId}`;

      const trackingOrderReq = await fetch(url, {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      });
      const trackingOrderRes = await trackingOrderReq.json();
      setTrackingDetails(trackingOrderRes);
      console.log(trackingOrderRes);
    } catch (error) {}
  };
  return (
    <>
      <Head>
        <title>track your order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="bg-gray-50">
        <Tracking {...trackingDetails} />
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
