import React from "react";
import Head from 'next/head'
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import Loginform from "../components/loginform";

export default function Signup(){
    return(
        <>
            <Head>
                <title>Sign up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar/>
            </header>
            <main class="">
                <Loginform/>
            </main>
            <footer>        
                <Footer/>
            </footer>
        </>
    )
}
