import React from "react";
import Head from 'next/head'
import Navbar from "../components/navbar";
import Form from "../components/Form";
import Footer from "../components/Footer";
import Tracking from "../components/tracking";

export default function Trackingpage(){
    return(
        <>
            <Head>
                <title>track your order</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar/>
            </header>
            <main className="bg-gray-50">
                <Tracking/>
            </main>
            <footer>
                <Footer/>
            </footer>
        </>
    )
}